# Generated by Django 6.0.1 on 2026-03-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_updated_at_alter_complaint_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Complaint', 'verbose_name_plural': 'User Complaints'},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Water', 'Water'), ('Road', 'Road'), ('Electricity', 'Electricity'), ('Garbage', 'Garbage'), ('Street Light', 'Street Light'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_index=True, default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='state',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], db_index=True, default='Pending', max_length=20),
        ),
    ]
