# Generated by Django 6.0.1 on 2026-03-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_notification_complaint_alter_notification_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='complaint',
        ),
    ]
